---
openvpn_easy_rsa_url: "https://github.com/OpenVPN/easy-rsa/releases/download/\
                       v{{ openvpn_easy_rsa_version }}/\
                       EasyRSA-{{ openvpn_easy_rsa_version }}.tgz"
openvpn_easy_rsa_dest: "/home/openvpn"
openvpn_home: "/home/openvpn"
openvpn_easy_rsa_server_name: "server"
openvpn_ta_enabled: true        # Enable tls-auth
