---
name: ansible-lint
# yamllint disable rule:truthy
on: [push, pull_request]
# yamllint enable rule:truthy

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible Collections
        run: ansible-galaxy collection install -r requirements.yml

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
