---
name: Check file sizes

# yamllint disable rule:truthy
on:
  workflow_dispatch:
# yamllint enable rule:truthy

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: freenet-actions/check-file-size@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
