---
- name: Configure user
  ansible.builtin.import_tasks:
    file: user.yml

- name: Install OpenVPN package
  ansible.builtin.import_tasks:
    file: install.yml

- name: Installation of EasyRSA
  ansible.builtin.import_tasks:
    file: easyrsa.yml
